workflows:
  flutter-android:
    name: Flutter Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      working_directory: meu_app_notificacoes
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Debug APK
        script: flutter build apk --debug
      - name: Build Release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - "seu-email@exemplo.com"
        subject: "Novo APK Flutter"
        body: "O build foi concluído com sucesso!"
