name: suportediario
description: Aplicativo para notificar agenda

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.5
  file_picker: ^8.3.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/audio/som1.mp3
    - assets/audio/som2.mp3


