name: suportediario
description: Aplicativo para notificar agenda

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0
  file_picker: ^8.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.seuprojeto.suportediario
        pluginClass: SuporteDiarioPlugin
