name: suportediario
description: Um aplicativo de suporte diário com notificações.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.1
  flutter_tts: ^3.6.0
  provider: ^6.0.5
  file_picker: ^10.3.2
  flutter_plugin_android_lifecycle: ^2.0.30
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/som1.mp3
    - assets/audio/som2.mp3



