name: meu_app_notificacoes
description: Aplicativo de agenda com notificações personalizadas, interface moderna inspirada no Nubank (azul escuro).
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^12.0.3
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_slidable: ^3.0.0
  timezone: ^0.9.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  file_picker: ^5.2.7
  flutter_tts: ^3.8.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/audio/som1.mp3
    - assets/audio/som2.mp3

platforms:
  linux:
    plugin: none
