name: meu_app_notificacoes
description: Aplicativo avançado de notificações com som personalizado
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/audio/som1.mp3
    - assets/audio/som2.mp3
